version: "3.1"
services:
  vicbdm:
    image: vicbdm
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - default
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
    environment:
      - DATABASE_URL="postgresql://postgres:example@localhost:5432/vicbdm?schema=public"
    restart: unless-stopped